# Generated by Django 5.0.1 on 2025-09-06 00:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0019_alter_student_guardian_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_free_session",
            field=models.BooleanField(
                default=False, verbose_name="تم اعتبارها حصة مجانية"
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="نسبة التخفيض (%)",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="free_sessions_remaining",
            field=models.PositiveIntegerField(
                default=0, verbose_name="حصص مجانية متبقية"
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="is_completely_free",
            field=models.BooleanField(
                default=False, verbose_name="مجاني بالكامل لهذا الفوج"
            ),
        ),
    ]
